### ISSUE TITLE
Navigation menu should be a solid color bar, with contrasting text colors or images

### ISSUE THREAD

**Issue by Justinzenki** [kaygee92/qawebsite#5]
Summary: Nav bar back ground color and contrasting text color missing

Severity/priority: 3/3

Version:1.0

Environment: Website

Expected: Nav bar to have background color and contrasting text color

Actual: Nav bar has no background color and contrasting text color

Steps to reproduce: Go to website and view nav bar at header of page

**Comment by kaygee92** [comment]
Changed the color to the nav bar
