### ISSUE TITLE
When each nav menu is hovered over, the background color and text color should change to indicate this; if images, some obvious indication should show the rollover

### ISSUE THREAD

**Issue by Justinzenki** [kaygee92/qawebsite#6]
Summary: When nav menu is hovered over, the background color and text color doesn't change to indicate hover or image rollover

Severity/priority: 3/3

Version: 1.0

Environment: Website

Expected: Nav bar background and text color to change when hovered or rolledover

Actual: Nav bar has no background color and text stays the same color

Steps to reproduce: Go to website nav bar and hover over text

**Comment by kaygee92** [comment]
Fixed and changed the color for the hover effect
